### ISSUE TITLE
中文环境时添加组件选择静态、图表、过滤器子类型都不能选择

### ISSUE THREAD

**Issue by daleyjh** [shzlw/poli#11]
中文环境时添加组件选择静态、图表、过滤器子类型都不能选择，这应该是个BUG吧，调成英文没问题

**Comment by shzlw** [comment]
谢谢使用Poli！我已经复现了， 是一个bug，我会在周末出一个v0.8.1来修复它。

**Comment by daleyjh** [comment]
> 谢谢使用Poli！我已经复现了， 是一个bug，我会在周末出一个v0.8.1来修复它。

好的，刚好有个需求用，就想起来poli了

**Comment by shzlw** [comment]
已在[v0.8.1](https://github.com/shzlw/poli/releases/tag/v0.8.1)修复。
