### ISSUE TITLE
有两个问题

### ISSUE THREAD

**Issue by iHappinessLife** [shzlw/poli#12]
1、mysql驱动问题
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

2、导出cvs显示乱码，而且文件名无法修改
![image](https://user-images.githubusercontent.com/37396786/61197828-77534180-a709-11e9-9f6a-d6c4bd063dbf.png)

**Comment by shzlw** [comment]
第一个问题是因为新的mysql jdbc driver用了新的driver class name，你试试用com.mysql.cj.jdbc.Driver，应该就不会报warning了。

第二个问题，我要去复现一下。请问在图表上也是现实乱码吗？
文件名修改暂时只能先下载再手工重命名。

**Comment by shzlw** [comment]
### 有光“导出cvs显示乱码“

我测试了一下使用中文，图表是显示正常，csv文件如果用notepad打开也显示正常，使用excel打开就是乱码。这有可能是导出的csv是utf-8格式的。

**Comment by iHappinessLife** [comment]
> ### 有光“导出cvs显示乱码“
> 我测试了一下使用中文，图表是显示正常，csv文件如果用notepad打开也显示正常，使用excel打开就是乱码。这有可能是导出的csv是utf-8格式的。

是的excel打开乱码。还有一个问题，部署后能否不要点击“Apply Filters”，实现自动交互？

**Comment by shzlw** [comment]
是有计划添加一个选项当filter被更改时，自动刷新。

**Comment by shzlw** [comment]
新选项auto filter已经被添加到新版本[v0.9.0](https://github.com/shzlw/poli/releases)中，可以在report page上修改，当filter被更改时，自动刷新。
