### ISSUE TITLE
请问一下，能在报表的语句配置中调用/ws/user/account返回的数据不？

### ISSUE THREAD

**Issue by Lzhaojie** [shzlw/poli#13]
你好，我想在报表配置语句中，限制当前登录的用户只能查看自己归属的区域数据，应该要怎么配置？

**Comment by Lzhaojie** [comment]
另外，还有一个问题是，过滤器中能使用其他过滤器吗？

**Comment by shzlw** [comment]
### 报表配置语句中，限制当前登录的用户只能查看自己归属的区域数据?

当前的[用户管理](https://shzlw.github.io/poli/#/user-management)实现比较简单，只能在viewer level限制报表的access。在roadmap上，我的确有想法在developer level上限制data source的access， 这样的话 developer 1只能用data source 1， developer 2 只能用data source 2，不知这样是否能满足你的需求？`

### 过滤器中能使用其他过滤器?

暂时不能，不过已经添加到roadmap上了。

**Comment by Lzhaojie** [comment]
这种方式如果用户的分类多样性的话，可能会有局限性。而且您目前这个版本在功能上其实已经是满足这个需求的了，相当我只要创建多张报表，再把其中的data source设置为不同的，再配给不同的角色，角色再配给不同的用户，也可以实现，但是这种方式只能局限于用户分类比较少跟单一才可以，跟你的想法其实同种效果。我在想，能否增加多一张用户的属性表，然后用户管理上可以配置要给用户增加的属性值，比如：增加一个属性值(city)，再给这个属性配置相应的值，然后在用户管理上，user1就可以编辑或者选择这个属性值city为北京、上海等值，而在用户登录时的account返回的JSON里加上这些属性性，在报表编辑脚本里可以调用把这些用户的属性值当作过滤器使用。

**Comment by shzlw** [comment]
Row Level Security已经在新版本[v0.9.0](https://github.com/shzlw/poli/releases)中加入。

**Comment by Lzhaojie** [comment]
你好，请问一下，我这边在用户里配置了属性值之后，在报表中的语句要怎么使用？

**Comment by shzlw** [comment]
详细文档请戳[这里](https://shzlw.github.io/poli/#/report-component?id=row-level-security)，我提供了一个实例。
