### ISSUE TITLE
全屏不能yo

### ISSUE THREAD

**Issue by yzy-china** [shzlw/poli#14]
full screen全屏模式不能用，点击后请进入登录页面

**Comment by shzlw** [comment]
我测试了使用chrome在admin和viewer role下点击全屏按钮和使用$apiKey都正常，请问能提供更详细的复现步骤吗？

**Comment by yzy-china** [comment]
admin登录-点击全屏-一闪而过-重复进入登录界面 （不能上传附件QQ30581565）

**Comment by yzy-china** [comment]
admin登录，打开地址
http://localhost:6688/workspace/report/fullscreen?$toReport=sqllite
重复进入登录界面

**Comment by yzy-china** [comment]
环境Xp
Firefox版本52.9.0 (32 位)
Chrome版本 49.0.2623.112

**Comment by yzy-china** [comment]
给你找到原因了，登录时选择“记住我”Firefox版本52.9.0 (32 位)可以全屏；Chrome版本 49.0.2623.112显示白板。

**Comment by shzlw** [comment]
谢谢！我已经在[v0.9.1](https://github.com/shzlw/poli/releases/tag/v0.9.1)里修复了这个问题。你的chrome版本有点低，可以试试更高级或者最新的版本吗?
