### ISSUE TITLE
关于drill through的问题

### ISSUE THREAD

**Issue by HEWill2019** [shzlw/poli#15]
在Report中定义drill through，运行时点击进入钻取的report，table的数据查询范围是全部，钻取条件不起作用，只有点击apply filters才能起作用，钻取的参数在url中能够看到。

**Comment by shzlw** [comment]
这个已经在新版本[v0.9.0](https://github.com/shzlw/poli/releases)中改进。

**Comment by HEWill2019** [comment]
我下载了 v0.9.0 但是同样问题还是存在，例如这个url：http://localhost:6688/poli/workspace/report/fullscreen?$toReport=sub1&$fromReport=main&Id=2
只有点击Apply Filters按钮，参数Id才能在查询中起作用；刚进入这一页面或者随时点击刷新按钮，都是查询出全部数据，参数Id不起作用。 Table的定义是：where 1=1 {{ and OrganId = CAST(:Id AS INTEGER)}}，浏览器是chrome。谢谢！

**Comment by shzlw** [comment]
不好意思，上次那个fix有点问题，我再重弄一下。

**Comment by shzlw** [comment]
我已经在[v0.9.1](https://github.com/shzlw/poli/releases/tag/v0.9.1)修复了这个bug。
