### ISSUE TITLE
源码启动

### ISSUE THREAD

**Issue by dawnsongpeng** [shzlw/poli#16]
我下载了你的源码，但是在启动过程中并没有反应.
![image](https://user-images.githubusercontent.com/53201318/61690746-a185ae80-ad5c-11e9-9d50-0010a8883ce5.png)

**Comment by shzlw** [comment]
开发和编译文档戳[这里](https://shzlw.github.io/poli/#/build)。我一般都是在terminal里用build编译，然后java -jar来启动。

**Comment by dawnsongpeng** [comment]
好的，谢谢
