### ISSUE TITLE
关于源码启动

### ISSUE THREAD

**Issue by navyflower** [shzlw/poli#17]
eclipse加载项目源码后，怎么通过run spring boot app的形式启动？或者有相关说明不？
想通过二次开发追加些内容，通过ide进行调试。
不胜感激。

**Comment by shzlw** [comment]
我不太清楚怎么在eclipse里用run spring boot app。开发和编译文档戳[这里](https://shzlw.github.io/poli/#/build)。我一般都是在terminal里用build编译，然后java -jar来启动。

**Comment by navyflower** [comment]
@shzlw 
> 我不太清楚怎么在eclipse里用run spring boot app。开发和编译文档戳[这里](https://shzlw.github.io/poli/#/build)。我一般都是在terminal里用build编译，然后java -jar来启动。

那你是通过哪种方式进行debug的？二次开发需要调试代码，要是通过java -jar启动的话，问题调查起来比较麻烦。

**Comment by shzlw** [comment]
我IDE用的intellj，然后如果是编译前端的话我是直接npm start，后端的话因为逻辑很简单，我一般直接写单元测试来调试，很少用断点。用eclipse的话，是不是可以直接右键run as application？
