### ISSUE TITLE
start.sh has DOS line endings

### ISSUE THREAD

**Issue by mmessmore** [shzlw/poli#19]
It has newline + carriage return line endings.  It should have Unix line endings since it is a shell script.

```
$ cat -vet start.sh
#!/bin/sh^M$
set -e^M$
^M$
java -jar poli-0.9.0.jar --spring.config.name=application,poli^M$
$ dos2unix start.sh
dos2unix: converting file start.sh to Unix format...
$ cat -e start.sh
#!/bin/sh$
set -vet$
$
java -jar poli-0.9.0.jar --spring.config.name=application,poli$
```

**Comment by chr15m** [comment]
Additionally the version of `start.sh` in the release is not executable - needs a `chmod 755 start.sh` in order to work. Since the version in the repository itself seems ok these both seem like build-time issues.

**Comment by shzlw** [comment]
Thanks for pointing those out. The line endings and the file permission are fixed in the [new release](https://github.com/shzlw/poli/releases/tag/v0.9.1) now .
