### ISSUE TITLE
GeneratedKeyHolder.getKey异常

### ISSUE THREAD

**Issue by navyflower** [shzlw/poli#22]
DB：postgres

创建报表、数据源、群组时报异常：
The getKey method should only be used when a single key is returned.  The current key entry contains multiple keys:

创建用户时没有问题。

原因：
创建时会返回table的所有列，直接通过keyHolder.getKey().longValue()就会报异常，
所以其他的dao中都应该按照userdao的代码修改下：
KeyHolder keyHolder = new GeneratedKeyHolder();
        npjt.update(sql, params, keyHolder, new String[] { User.ID});
        return keyHolder.getKey().longValue();
而不是
KeyHolder keyHolder = new GeneratedKeyHolder();
        jt.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, name);
            return ps;
        }, keyHolder);
        return keyHolder.getKey().longValue();

**Comment by shzlw** [comment]
非常感谢！

**Comment by dmdevito** [comment]
It looks like the same pb I face when using Poli with Postgresql (PG), like within this WE.

PG driver seems not able to process, as expected, the following line:

PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

Note: I am using the latest version (42.2.6) of the PG driver.

So, a solution may be to replace the line above with:

PreparedStatement ps = connection.prepareStatement(sql, new String[]{"id"} );

Note : there should be more than a line to replace within the Poli source code.

Unfortunately, I have not been able yet to test this modification, as "npm install" returns "Maximum call stack size exceeded".. and I have not found a way to bypass this npm pb.

**Comment by dmdevito** [comment]
OK, it works when replacing

PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

with 

PreparedStatement ps = connection.prepareStatement(sql, new String[]{"id"} );

Note: 4 places within the code to replace.

**Comment by dmdevito** [comment]
I should have sync with master before writing posts above, as you have fixed very recently the pb... 

After having downloaded the latest source, compiled it, I have seen that the pb, I have previously met, has disappeared now.

Thanks.

**Comment by shzlw** [comment]
[v0.9.1](https://github.com/shzlw/poli/releases/tag/v0.9.1) is now released which contains the fix for this issue.
