### ISSUE TITLE
Query Limit?

### ISSUE THREAD

**Issue by fishmichael** [shzlw/poli#27]
Zhonglu,

Created a couple of table components with queries against our DB2 database on the iSeries.  Noticed that it is consistently only returning 1000 rows of data.  I don't see anywhere to configure number of rows returned.  Is this a hard-coded limitation?

Thanks,

Mike

**Comment by shzlw** [comment]
Please try modify the [poli.maximum-query-records](https://shzlw.github.io/poli/#/configuration?id=number-of-query-results) in the poli.properties. 

Sounds like the default value is a bit confusing for the init setup. I will consider to change the default value to unlimited.

**Comment by fishmichael** [comment]
Zhonglu,

That is perfect.  I see the relevance of globally limiting the rows
returned (some of our tables have 15 million rows).

For me I like to limit the rows returned in the query itself, however.
Short of a dialog on the Query tab itself so that I could specify maximum
rows per query (that would be great), I will just modify the SQL itself.

Thanks again for your prompt response!

Mike
