### ISSUE TITLE
为什么将p_report、p_component、p_canned_report中的json类型改为了varchar?

### ISSUE THREAD

**Issue by navyflower** [shzlw/poli#29]
0.9.0中postgresql的p_report、p_component、p_canned_report表中定义了相关json类型，虽然有bug，但是修正下即可，例如ReportDao的insert：
	PGobject jsonObject = new PGobject();
        jsonObject.setType("json");
        try {
			jsonObject.setValue(style);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	params.addValue(Report.STYLE, jsonObject);
0.9.1中将相关json类型都变更为varchar了，这样做会产生一些问题：
长度限制、varchar不能像json那样进行检索等等

**Comment by shzlw** [comment]
是这样的，当时测试的时候发现如果用json类型，jdbc url就要加stringtype=unspecified，才可以运行， 我文档还没有写，所以先改成了varchar，这样直接就可以用。

试一下用stringtype=unspecified和json列类型， 你就不用修改Dao里的代码了。Dao里我还是情愿用标准的SQL功能，这样如果有人要用MySQL或者其他的数据库也可以直接用。

PostgreSQL, varchar没有长度限制和text是一样的。查询的话，如果你修改你的SQL语句，把select里把列转成json型应该也是可以的。

**Comment by navyflower** [comment]
@shzlw 
有道理，3Q
