### ISSUE TITLE
建议增加个0.50到0.6.0版本升级的说明

### ISSUE THREAD

**Issue by cubemoon** [shzlw/poli#3]
目前把0.5.0的数据库复制到0.6.0中报了很多错误

**Comment by shzlw** [comment]
感谢试用Poli! 嗯，0.6.0的数据库表没有变化，但是修改了bar/line/area图表的一些字段值，有可能导致了crash，我会排查一下，看是否能提供版本升级的步骤，项目还在早期开发中，还没有到1.0.0的稳定版本，如果有break backwards compatible的错误，还请多多包涵。。。

**Comment by shzlw** [comment]
我试了一下用0.6.0的jar连接0.5.0的测试数据库，我发现的错误是所有bar/line/area都没有显示数据，页面可以正常显示，也没有其他报错。修复的方法是，在页面上修改 这些图表的值，0.5.0是只有key和value，0.6.0修改成了X-axis和Y-axis.

如果你看到的不是这个错误，能不能告知下你是如何复制数据库的，因为两个版本的schema是一样的，你可以直接备份你0.5.0的数据库（复制黏贴成另一个文件就可以了），然后重新在poli.properties里指向旧版本的数据库，看看是否可行。

**Comment by cubemoon** [comment]
编译报错是我的操作失误，目前现象确实是report中bar/line/area都没有数据显示了。又要从新点选一遍
最后感谢作者的工作付出，希望尽快能够看到1.0稳定版。
