### ISSUE TITLE
【优化】报表列表

### ISSUE THREAD

**Issue by czy1994** [shzlw/poli#31]
目前的报表列表是一下子罗列所有报表，是否以目录树方式存放会更好些？

**Comment by shzlw** [comment]
是的，的确有计划在0.10版本里，提供可以把多个report归到一个project里，并加入一个favorite组。

**Comment by czy1994** [comment]
嗯嗯，这样会方便管理一点。再提个想法，是否提供多租户方式的报表系统，比方 租户A：专门设计A业务系统报表，租户B：设计B业务系统报表。

**Comment by shzlw** [comment]
能不能举个再具体点的例子？现有的[用户组](https://shzlw.github.io/poli/#/user-management)允许多个developer role同时设计report。

**Comment by czy1994** [comment]
我是指sass那种多租户架构，既可以在主系统上新增租户A时，该租户A会有一个专门的url地址，有自己的一套用户、角色、权限、报表、数据源。 租户A  和  租户B 是逻辑隔离的，双方不会看到对方的数据。

**Comment by shzlw** [comment]
LOL 弄成SaaS那样就要卖钱了，就要变成poli cloud了，这个是在roadmap上不过优先级很低，暂时优先级还是放在完善其他功能上。

**Comment by czy1994** [comment]
是的，我是觉得这个项目挺好的哈哈，想到啥好的就提一下建议。是的，sass那样是可以卖钱了

**Comment by shzlw** [comment]
新版本[v0.10.0](https://github.com/shzlw/poli/releases)中已加入favourite菜单和目录树方式显示report。
