### ISSUE TITLE
Default value for parametr in filter commponent

### ISSUE THREAD

**Issue by martinjanda** [shzlw/poli#34]
Poli is awesome project, thank you.

Can you add default value for filter commponent? Sometimes parametr without value will cause heavy query or internal error.

**Comment by shzlw** [comment]
Implement the new feature in [v0.10.0](https://github.com/shzlw/poli/releases/tag/v0.10.0) to allow setting default parameter value for filter component.

**Comment by martinjanda** [comment]
Awsome, thank you.
