### ISSUE TITLE
docker安装短时间自动退出，分享链接不可用

### ISSUE THREAD

**Issue by shulinqian** [shzlw/poli#38]
登录几分钟，就会自动退出登录，
分享连接打开显示 The report is no longer available.

按照文档docker安装的

**Comment by czy1994** [comment]
环境：从0.9.1升级到0.10.0（通过脚本升级）
分享链接确实有bug：
1、在分享有效期内，打开显示无效；
  http://ww1.sinaimg.cn/large/006y4X83gy1g5zabvhm8uj31h90c3jt0.jpg
  http://ww1.sinaimg.cn/large/006y4X83gy1g5zabxuxzzj30p904kjrd.jpg
2、打开某一分享报告，显示另一个分享报告；
  http://ww1.sinaimg.cn/large/006y4X83gy1g5zabzrfrbj31gx0c8abo.jpg
  http://ww1.sinaimg.cn/large/006y4X83gy1g5zac2kpr1j31a505i0t2.jpg

**Comment by shzlw** [comment]
谢谢测试，我在[v0.10.1](https://github.com/shzlw/poli/releases/tag/v0.10.1)修复了好几个分享的问题。
