### ISSUE TITLE
图表配置sql的时候，用了as但是列名称还是原始的数据库里的字段名称

### ISSUE THREAD

**Issue by null64** [shzlw/poli#39]
图表配置sql的时候，用了as但是列名称还是原始的数据库里的字段名称，现阶段采用cast的方式进行转换后，把展现的列名变了。

**Comment by null64** [comment]
mysql

**Comment by suxg003** [comment]
出现同样问题，标头无法映射中文，求解决。数据库5.6.34--5.7.x 都有此问题

**Comment by shzlw** [comment]
我已经在当前版本复现了，在我本地已经修复，这周会发一个新的补丁。

![mysql_alias](https://user-images.githubusercontent.com/4129280/70489856-d2c40880-1aca-11ea-8344-38ba2c218db8.png)
