### ISSUE TITLE
Oracle Data Source

### ISSUE THREAD

**Issue by netesheng** [shzlw/poli#45]
Does the data source support Oracle? How to create a connection URL and other information?

**Comment by netesheng** [comment]
支持Oracle数据吗？怎么创建？连接信息该怎么填写？

**Comment by shzlw** [comment]
支持的，你需要查看[安装手册](https://shzlw.github.io/poli/#/installation)，下载相对应的oracle JDBC driver。 JDBC URL格式是根据你oracle的配置，比如如果是使用SID，就用jdbc:oracle:thin:@host:port:sid。

**Comment by netesheng** [comment]
好的  感谢！

**Comment by netesheng** [comment]
![111](https://user-images.githubusercontent.com/9253891/98652142-28a5ce00-2376-11eb-9edd-1c2a88465eb4.jpg)
![QQ截图20201110165719](https://user-images.githubusercontent.com/9253891/98652150-2ba0be80-2376-11eb-9edf-96dfdb4582ee.jpg)
版本 0.12.2 已经将oracle jdbc文件放置jdbc-drivers 数据源设置也设置了 还是报错 是哪里设置有问题么？

**Comment by netesheng** [comment]
连接URL试过使用jdbc:oracle:thin:@10.3.4.41:1521:branch或者jdbc:oracle:thin:10.3.4.41:1521:branch或jdbc:oracle:thin:10.3.4.41:1521/branch或jdbc:oracle:10.3.4.41:1521:branch等等 都不行 难道问题不在这一块么？

**Comment by shzlw** [comment]
可以试一下以下两个改动吗？
1. jdbc-drivers目录下就放一个单独的ojdbc6.jar
2. 驱动类名用： oracle.jdbc.driver.OracleDriver

**Comment by netesheng** [comment]
![云之家图片20201111130240](https://user-images.githubusercontent.com/9253891/98770907-39118380-241e-11eb-8a84-3f2d7aaaad13.png)
![QQ截图20201111130211](https://user-images.githubusercontent.com/9253891/98770910-3adb4700-241e-11eb-8638-bb0ed7f0563a.jpg)
已经按照你的方法 确实可行
