### ISSUE TITLE
How to split /static/js/2.39a8b735.chunk.js ?

### ISSUE THREAD

**Issue by kabowo** [shzlw/poli#46]
I am using Windows for server. I have been setting inbound port in the firewall, but still can't show the page. On localhost is working properly.
I have an idea, how to split IP:6688/static/js/2.39a8b735.chunk.js ? because that file size is 1.8 MB

Thanks in advance

**Comment by shzlw** [comment]
For the firewall, allowing the inbound port should be enough. Not sure why it doesn't work for you.

The js file is bundled. What do you mean by split it? If you want to serve it on a CDN, you will need to manually modify the index.html to point to the js file you host somewhere.

**Comment by shzlw** [comment]
The front end is in react and the folder web-app is inited by using [create-react-app](https://github.com/facebook/create-react-app). You probably need to check that out to see if it provides the option you need.

**Comment by kabowo** [comment]
Thanks @shzlw  , i have succeeded in changing on build configuration.
