### ISSUE TITLE
源码启动后报错

### ISSUE THREAD

**Issue by suxg003** [shzlw/poli#53]
错误信息如下：环境 mac +jdk1.8+Eclipse sts4
 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.

增加pom.xml 文件
<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-reflect</artifactId>
			<version>1.3.50</version>
		</dependency>
后，启动无日志输出，无报错信息。页面无法访问

**Comment by shzlw** [comment]
这个只是warning吧，不影响启动和运行。build请参考[这里](https://shzlw.github.io/poli/#/build)。
