### ISSUE TITLE
关于fileter 的问题与真分页问题

### ISSUE THREAD

**Issue by suxg001** [shzlw/poli#55]
1、当设置fileter后为slicer后，在query里编写自己的查询条件，但是slicer只是多选，能否添加一个下拉组件。谢谢

2、当数据量很大时，默认的1000行加载不太满足，
解决方案：能否让用户获取 “当前页数”和“下一页数” 来让用户实现真分页。谢谢

**Comment by shzlw** [comment]
1. 添加一个dropdown是可以是现实的。
2. Slicer或者其他所有组件分页的问题，其实很早就想过了。当时没有实现的原因是因为想到不同数据库的分页语法不一样。举个例子，比如用mysql，分页可以写成 SELECT * FROM table LIMIT 5,10; 如果用postgresql，分页可以写成 SELECT * FROM table OFFSET 5 LIMIT 10; 

现在再思考一下，其实是可以加一个新的语法，可以写成 SELECT * FROM table LIMIT @page_offset,@page_size 或者 SELECT * FROM table OFFSET @page_offset LIMIT @page_size;

有空的话我会再看一下。

**Comment by suxg001** [comment]
首先非常感谢您的回复，建议分页算法可以在后台写为一个统一真分页算法，
比如 只要(当前页 - 1) * 每页显示大小， 不同数据库可以通过 数据源驱动或者数据源url 前缀来获得

另外，你项目的源码我还是跑不起来，能出一个简单运行的文档或者wiki吗，谢谢

**Comment by shzlw** [comment]
Build的文档在[这里](https://shzlw.github.io/poli/#/build)
安装的文档在[这里](https://shzlw.github.io/poli/#/installation)

**Comment by suxg001** [comment]
就是按这个文档部署的build后，项目无法启动，后台也不报错

**Comment by suxg001** [comment]
我大概知道原因了是这个项目只能依赖与构建后，后台以打包jar的方式给前台react 使用对吗？

**Comment by shzlw** [comment]
基本流程是前台react被编译，打包，然后移到spring boot里，最后build java文件成一个可执行jar.

**Comment by shzlw** [comment]
不启动的话，log里面应该会报错的。

**Comment by suxg001** [comment]
好的，非常感谢，那我的问题应该出在react 上，对react前端不熟悉，我的上mac系统，Eclipse下 直接启动App后不报错。

**Comment by suxg001** [comment]
后台运行app后，启动台没有出现springboot 加载启动日志，感觉应该是线程等待了。。。。

**Comment by suxg001** [comment]
10:57:17.317 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.

**Comment by shzlw** [comment]
我开mac试了一下，不好意思，那个build.sh少了一些语句导致static folder没有被创建在src/main/resources下。

我已经修改了，你可以再试一下。

**Comment by suxg001** [comment]
好的，我pull下试试，非常感谢

**Comment by suxg001** [comment]
首页能进去了，但登陆按钮无法进入，前端代码异常，能否加个微信？
createError.js:17 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.p.<computed> (xhr.js:78)
auth/login/user:1 Failed to load resource: the server responded with a status of 500 ()
createError.js:17 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.p.<computed> (xhr.js:

**Comment by suxg001** [comment]
element.style {
}
.app, body, html {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    font-family: Tahoma,Geneva,sans-serif;
    color: #091e42;
    background-color: #f5f5f5;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    transition: all .15s ease;
}
user agent stylesheet
body {
    display: block;
    margin: 8px;
}
user agent stylesheet
html {
    color: -internal-root-color;
}
﻿
xhr.js:173 POST http://localhost:6688/auth/login/user 500
createError.js:17 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.p.<computed> (xhr.js:78)
﻿
​
后台无日志打印，看上去是auth/login/user  这个有问题

**Comment by suxg001** [comment]
是数据源poli.db的原因，log-back.xml文件删除后，可出日志，后续我配置一下
