### ISSUE TITLE
Component Types

### ISSUE THREAD

**Issue by CMaclellan** [shzlw/poli#6]
Would it be possible to create a Dynamic component type that allows for a query input and a plain text, or html output can can be customized to display the query results?

example: 
_Component to display the number of currently active sessions._ 
Currently the only way to achieve this is to put it out to a table.

**Comment by shzlw** [comment]
Yes, the single value/metric/kpi component is on the roadmap for v0.8.0 release.

**Comment by shzlw** [comment]
v0.8.0 is released and please try out the [Card component](https://shzlw.github.io/poli/#/report-component?id=card).
