### ISSUE TITLE
如何创建dashboard

### ISSUE THREAD

**Issue by junphine** [shzlw/poli#66]
我看首页有很丰富的dashboard，但是实际操作过程中没找到这个功能

**Comment by shzlw** [comment]
dashboard功能试试戳[这里](https://shzlw.github.io/poli/#/quick-start)。

**Comment by junphine** [comment]
> dashboard功能试试戳[这里](https://shzlw.github.io/poli/#/quick-start)。

然而，并没有找到啊，只有创建report的过程。难道需要把report以iframe嵌入dashboard？

**Comment by shzlw** [comment]
这个项目没有实现dashboard， 首页上你看到的有可能是全屏下的report。
