### ISSUE TITLE
图表使用多系列的时候有问题

### ISSUE THREAD

**Issue by mxlib** [shzlw/poli#69]
全部聚集到X轴第一个值上

**Comment by shzlw** [comment]
Poli刚刚发布了[v0.12.0](https://github.com/shzlw/poli/releases/tag/v0.12.0)。我升级了echarts的版本，你可以再试一下，看看问题还存在吗？

**Comment by mxlib** [comment]
还是有问题

**Comment by mxlib** [comment]
[数据结果集](https://raw.githubusercontent.com/mxlib/mxlib/master/1.png)
[组件配置](https://raw.githubusercontent.com/mxlib/mxlib/master/2.png)
[最终展现](https://raw.githubusercontent.com/mxlib/mxlib/master/3.png)

**Comment by shzlw** [comment]
Sorry, 我理解错你的问题了- -! 谢谢截图，我会试着复现一下。

**Comment by shzlw** [comment]
我已经复现了，发了个新的补丁[v0.12.1](https://github.com/shzlw/poli/releases/tag/v0.12.1)修复这个问题。

**Comment by mxlib** [comment]
> 我已经复现了，发了个新的补丁[v0.12.1](https://github.com/shzlw/poli/releases/tag/v0.12.1)修复这个问题。

还是有问题
![1](https://user-images.githubusercontent.com/17589907/81919620-a7f65700-960a-11ea-80eb-67aee3fb676e.png)

**Comment by shzlw** [comment]
我在新的补丁[v0.12.2](https://github.com/shzlw/poli/releases/tag/v0.12.2)里加了默认值，这样bar和line就会显示连续值了。
