### ISSUE TITLE
Unauthorized: The request is unauthorized.

### ISSUE THREAD

**Issue by easyfor** [shzlw/poli#70]
你好，我设置一个Viewer用户进行登录后查看报表提示：Unauthorized: The request is unauthorized.然后回到登录页面。该用户已经添加到一个用户组，而且该用户组也添加了报表。这个请问要如何处理？

**Comment by shzlw** [comment]
谢谢使用，问题已经复现了。会在下周新的release中修复。

**Comment by shzlw** [comment]
我试了一下，v11的release中没有这个问题，你应该是build from source吧，问题是出在AuthFilter， 在其他地方我重构了路径名，这里漏改了。

**Comment by shzlw** [comment]
Poli刚刚发布了[v0.12.0](https://github.com/shzlw/poli/releases/tag/v0.12.0)。这个问题在source里也已经修复了。

**Comment by easyfor** [comment]
非常感谢！
