### ISSUE TITLE
Blank screen when a query runs

### ISSUE THREAD

**Issue by jtclaib** [shzlw/poli#73]
I have a simple query being used when adding a new component.  When the count(PoolID) is added and I run the query the screen goes blank.  There are other queries in the report that use count as well, they do not have this issue.  I created a view and stuffed the query in it, and thay seems to work.

Here is the component configuration
![PoliComponent](https://user-images.githubusercontent.com/23224452/82351513-8651f280-99b1-11ea-98e9-e9a4eb1dadfd.PNG)

here is the error  - 
![PoliError](https://user-images.githubusercontent.com/23224452/82352006-3889ba00-99b2-11ea-8338-136225cf9c81.PNG)

**Comment by shzlw** [comment]
Looks like the back end is returning 500 error for some reasons. Could you check if the log file located at log/server.log has additional error information?

In addition, your query seems to have an error. You select PolID but group by PoolID?
