### ISSUE TITLE
Any plan to support RLS(Row Level Security)?

### ISSUE THREAD

**Issue by archongum** [shzlw/poli#9]
For example. 
User account belong to USA can only see USA data and UK to UK data etc.

Metabase enterprise version implement RLS maybe like this:
1. Add additional global K/V attributes to User.
2. Query append all those K/V parameters.

**Comment by shzlw** [comment]
New feature: row level security has been implemented in the new release[v0.9.0](https://github.com/shzlw/poli/releases).

**Comment by archongum** [comment]
LGTM. Appreciate it!
